apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ho51kmpx4-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ho51kmpx4-dotnet-basic-gitops